import type { Metadata } from "next";
import "./globals.css";
import { inter, noto, sourceCode } from '@/app/fonts'

// If loading a variable font, you don't need to specify the font weight

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${noto.variable} ${sourceCode.variable} antialiased font-sans bg-neutral-100 dark:bg-neutral-700`}
            >
                {children}
            </body>
        </html>
    );
}
